Repository juarezCode/DemoAlbum, pull requests merged in 2019-08, with the labels that each got.

#3 creacion de cliente retrofit
  app/src/main/java/com/mediomelon/demoalbum/api/ServiceClient.java
Labels: help wanted

#4 Revert "creacion de cliente retrofit"
  app/src/main/java/com/mediomelon/demoalbum/api/ServiceClient.java
Labels: bug

#5 creacion de cliente retrofit
  app/src/main/java/com/mediomelon/demoalbum/api/ServiceClient.java
Labels: bug

#6 creacion de toolbar
  app/src/main/res/layout/toolbar.xml
Labels: enhancement

#8 creacion de toolbar 2
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/res/layout/toolbar.xml
Labels: enhancement

#9 creacion client retrofit
  app/src/main/java/com/mediomelon/demoalbum/api/IAlbumService.java
  app/src/main/java/com/mediomelon/demoalbum/api/IPhotoService.java
  app/src/main/java/com/mediomelon/demoalbum/api/IUserService.java
  app/src/main/java/com/mediomelon/demoalbum/api/ServiceClient.java
Labels: enhancement

#10 creacion de toolbar corregido
  app/src/main/res/layout/toolbar.xml
Labels: enhancement

#11 Creacion BottomNavigation
  app/src/main/res/layout/view_bottom_navigation.xml
Labels: enhancement

#12 servicio users
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mediomelon/demoalbum/api/IUserService.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IUser.java
  app/src/main/java/com/mediomelon/demoalbum/model/UserInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/model/entity/User.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/UserPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
Labels: enhancement

#14 Arreglo bug BottomNavigation
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
Labels: enhancement

#15 Creación de servicio álbumes
  app/src/main/java/com/mediomelon/demoalbum/api/IAlbumService.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IAlbum.java
  app/src/main/java/com/mediomelon/demoalbum/model/AlbumInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/model/entity/Album.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/AlbumPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/fragments/AlbumFragment.java
Labels: enhancement

#16 Creacion pantalla users
  app/src/main/java/com/mediomelon/demoalbum/adapter/UserAdapter.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IUser.java
  app/src/main/java/com/mediomelon/demoalbum/model/UserInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/UserPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/fragments/UserFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cardview_user.xml
  app/src/main/res/layout/fragment_user.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#17 correcion de toolbar
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/toolbar.xml
Labels: enhancement

#18 creacion pantalla detalles usuarios
  app/src/main/java/com/mediomelon/demoalbum/adapter/UserAdapter.java
  app/src/main/java/com/mediomelon/demoalbum/view/DetailUserActivity.java
  app/src/main/res/layout/activity_detail_user.xml
  app/src/main/res/layout/toolbar.xml
Labels: enhancement

#19 correccion de pantalla detalles usuarios
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mediomelon/demoalbum/view/DetailUserActivity.java
Labels: enhancement

#20 Creación pantalla detalles Usuarios
  app/src/main/java/com/mediomelon/demoalbum/view/DetailUserActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/res/layout/activity_detail_user.xml
Labels: enhancement

#21 pantalla users
  app/src/main/java/com/mediomelon/demoalbum/model/entity/User.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/fragments/UserFragment.java
Labels: enhancement

#22 Creación de pantalla albums
  app/src/main/java/com/mediomelon/demoalbum/adapter/AlbumAdapter.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IAlbum.java
  app/src/main/java/com/mediomelon/demoalbum/model/AlbumInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/model/entity/Album.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/AlbumPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/MainActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/fragments/AlbumFragment.java
  app/src/main/res/layout/cardview_album.xml
  app/src/main/res/layout/fragment_album.xml
Labels: enhancement

#23 creacion photos service
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mediomelon/demoalbum/api/IPhotoService.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IPhotos.java
  app/src/main/java/com/mediomelon/demoalbum/model/PhotoInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/model/entity/Photo.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/PhotoPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/PhotosActivity.java
  app/src/main/res/layout/activity_photos.xml
Labels: enhancement

#24 creacion pantalla fotos
  app/src/main/java/com/mediomelon/demoalbum/adapter/PhotoAdapter.java
  app/src/main/java/com/mediomelon/demoalbum/interfaces/IPhotos.java
  app/src/main/java/com/mediomelon/demoalbum/model/PhotoInteractor.java
  app/src/main/java/com/mediomelon/demoalbum/presenter/PhotoPresenter.java
  app/src/main/java/com/mediomelon/demoalbum/view/DetailUserActivity.java
  app/src/main/java/com/mediomelon/demoalbum/view/PhotosActivity.java
  app/src/main/res/drawable/progresbar.xml
  app/src/main/res/layout/activity_detail_user.xml
  app/src/main/res/layout/activity_photos.xml
  app/src/main/res/layout/cardview_photos.xml
Labels: enhancement
